name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        command: clean
    - name: install llvm tool
      run: rustup component add llvm-tools-preview
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        RUSTFLAGS: -Cinstrument-coverage
        LLVM_PROFILE_FILE: "codecov-%p-%m.profraw"
      run: cargo test --verbose
    - name: install grcov
      run: cargo install grcov
    - name: run grcov
      run: |
        grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        verbose: true
        fail_ci_if_error: true

